### ISSUE TITLE
Does it work for plain old javascript objects? 

### ISSUE THREAD

**Issue by wzup** [dzhibas/SublimePrettyJson#96] opened 2018-05-09 13:42 UTC
Difference. So question is does plugin sort objects in `.js` files? Looks like it doesn't. Or how do I configure it to work?
```javascript
// JSON
{
    "string": "string",
}

// Object.
// BOOM! Plugin doesn't sort it
{
    string: 'string'
}
```

**Comment by TheSecEng** [comment] 2020-04-18 02:37
Duplicate of #43

**Closed by TheSecEng** 2020-04-18 02:37 UTC
