### ISSUE TITLE
Strings inside of arrays get modified in some cases

### ISSUE THREAD

**Issue by tryashtar** [dzhibas/SublimePrettyJson#134] opened 2021-05-18 08:46 UTC
Sorry if this is a duplicate, I couldn't find anything.
When I format this JSON, the string inside gets modified to include spaces:
```py
# array changes
["a,b,c"]
    ↓
["a, b, c"]

# object is fine though
{"a,b,c":"a,b,c"}
    ↓
{
   "a,b,c": "a,b,c"
}
```

**Comment by TheSecEng** [comment] 2021-05-25 23:05
Is this still occurring? I am not able to reproduce this at all

https://user-images.githubusercontent.com/32599364/119579322-03593a00-bd73-11eb-84f0-3de50b1aa3ca.mp4

**Comment by tryashtar** [comment] 2021-05-25 23:07
Oh, it looks like it only happens for me when `keep_arrays_single_line` is set to true in the settings

**Comment by TheSecEng** [comment] 2021-05-25 23:08
Great catch, working on a fix

**Comment by TheSecEng** [comment] 2021-05-25 23:51
Fixed in latest release. Please allow a 3 hour window for Package Control to pull new release

**Closed by TheSecEng** 2021-05-25 23:51 UTC
Labels: bug, issue fix identified, next release

**Comment by tryashtar** [comment] 2021-05-26 03:21
Thank you so much! You rock 😄

**Comment by tryashtar** [comment] 2021-05-28 08:39
Oh by the way, quick question... I just updated, and now it really likes formatting lists like this:
```json
[1,
   2,
   3]
```
Did something weird change? Is there a new setting I missed?

**Comment by TheSecEng** [comment] 2021-05-29 05:24
Will look into this

**Comment by tryashtar** [comment] 2021-05-30 23:36
That's the entire snippet; if I write
```json
[1,2,3]
```
and format it, that's the result I get.

It probably has something to do with Sublime 4 and might be my fault... here are my settings though:
```json
{
    "max_arrays_line_length": 100,
    "indent": 3,
    "keep_arrays_single_line": true,
    "brace_newline": false,
    "bracket_newline": false
}
```

**Comment by tolyanja** [comment] 2021-05-31 07:03
Hello! i have same problem!
maybe problem was in os.linesep. i tried to change `content.split(os.linesep)` to `content.split('\n') `and it works.

**Comment by tryashtar** [comment] 2021-06-11 05:44
@tolyanja That fixed it for me too, until I realized that it breaks objects in lists.
```json
[{"a":"b"}]
    ↓
[{, "a": "b", }]
```

**Comment by TheSecEng** [comment] 2021-06-11 14:02
Is the video here what you would expect ?

https://github.com/dzhibas/SublimePrettyJson/issues/138

**Comment by tryashtar** [comment] 2021-06-11 16:09
That looks fine to me, although with a line that long I'd probably want it to do multiline, I think there's a setting for that

**Comment by TheSecEng** [comment] 2021-06-12 14:26
Fixed with latest release
