### ISSUE TITLE
PrettyJson does not prettify JSON with multiple lines

### ISSUE THREAD

**Issue by vietzerg** [dzhibas/SublimePrettyJson#82] opened 2017-05-15 08:47 UTC
When I tried to prettify a JSON file with multiple lines, Sublime Text said `Extra data: line 2 ... - line 20123`.

A preview of my JSON file:
![image](https://cloud.githubusercontent.com/assets/26194721/26049594/bb9d055e-3985-11e7-8312-0c1d942be297.png)

Please address this! Thank you!

**Comment by davidAlfonsoHermelo** [comment] 2018-01-09 22:35
I have the exact same problem. It would be nice if it was resolved.

**Comment by TheSecEng** [comment] 2020-04-16 12:55
@davidAlfonsoHermelo @vietzerg do you have a sample set of json to test this?

**Comment by TheSecEng** [comment] 2020-04-18 00:33
Duplicate of #72 

Will implement soon

**Closed by TheSecEng** 2020-04-18 00:33 UTC
