### ISSUE TITLE
UPGRADE - ImportError: No module named 'Pretty JSON.PrettyJsonListeners'

### ISSUE THREAD

**Issue by leoamsbb** [dzhibas/SublimePrettyJson#116] opened 2020-04-21 12:10 UTC
I am not getting prettify/minify options. Please find below screenshot for reference.
This I started facing this week itself, I am not sure what changed though.

Details:
System: MacOs Mojave [10.14.6]
Sublime version: 3.2.2  Build: 3211
Pretty JSON Package version: v1.0.3

<img width="1440" alt="PrettyJson_NoOptions_21Apr2020" src="https://user-images.githubusercontent.com/45357473/79864199-add78e80-83f6-11ea-90eb-e22ac152a730.png">

**Comment by nrabinowitz** [comment] 2020-04-21 18:34
Same, I no longer see the `format` option and the keyboard shortcut doesn't work since the latest package update.

**Comment by nrabinowitz** [comment] 2020-04-21 18:42
In my case this looks the same as #115 

Console:
```
reloading settings Packages/Pretty JSON/Pretty JSON.sublime-settings
reloading plugin Pretty JSON.PrettyJson
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Pretty JSON.PrettyJson'
reloading plugin Pretty JSON.PrettyJsonListeners
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Pretty JSON.PrettyJsonListeners'
```

**Comment by w84miracle** [comment] 2020-04-22 06:56
Encountered the same issue after I enabled [zsh plugin for sublime](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/sublime)
I haven't found the root cause, but I think it's related to python version issue.

A quick workaround is to disable the plugin:
check your ~/.zshrc if you're using ohmyzsh
`plugins=(git osx tmux sublime)`
removing `sublime` from it and relaunch.

**Comment by mrunal-badhe** [comment] 2020-04-22 07:44
I do not have sublime plugin enabled in zsh though.

plugins=(git)

**Comment by dzhibas** [comment] 2020-04-22 14:13
@TheSecEng can you please take a look at this? I think with recent changes something goes wrong for ST3

**Comment by TheSecEng** [comment] 2020-04-22 14:14
Looking now, St3 and St4 branches are seperate and ST3 changes have been minimal. Will work on this now.

**Comment by frank-weindel** [comment] 2020-04-22 14:25
I'm also a long time user of this package and noticed it completely stopped working for me a few days ago presumably after an auto-update

**Comment by TheSecEng** [comment] 2020-04-22 14:26
@mrunal-badhe @nrabinowitz @w84miracle 

Testing on:
- 3211 
- osx x64 
- channel: stable

Looks to be an issue with how PC handles none semantic version (`2019-01-01-01-0000`) and semantic version (`0.0.0`) and when we switch from branch release (Which is deprecated) to tag release, PC can get confused on upgrading to the tag release and can cause this reload issue.

This doesn't appear to happen every time.

**Workaround**

1. Remove Pretty JSON
1. Reinstall Pretty JSON

**Next Steps for Me**

- Investigate permanent solution for the switch from branch to tag release

**Comment by TheSecEng** [comment] 2020-04-22 14:27
@frank-weindel see above

**Comment by frank-weindel** [comment] 2020-04-22 14:37
@TheSecEng Thanks! I'm a mac user and its also affecting me: Sublime 3.2.1. Removing and reinstalling did not work.

**Comment by frank-weindel** [comment] 2020-04-22 14:38
Removing and reinstalling did not work for me.

**Comment by TheSecEng** [comment] 2020-04-22 14:39
Can you provide console output?

**Comment by TheSecEng** [comment] 2020-04-22 14:47
Also, did you do a quit on ST after reinstall ?

**Comment by TheSecEng** [comment] 2020-04-22 15:16
@frank-weindel @mrunal-badhe @nrabinowitz @w84miracle

@dzhibas for transparency

This is indeed a PackageControl / ST3 Issue. This happens when moving from a `.no-sublime-package` release to a packaged release. It happens because even though ST unloads the old version, it doesn't exactly purge `importlib` cache so ST still thinks it's installed at `Packages/` and then fails to load it as it now lives at `Installed Packages/`. Doing a full quit of ST should resolve this by forcing the cache to be cleared and it will then be loaded from the correct location.

**Note**
This is actually resolved in ST4 and this issue does not occur.

**Workaround**

1. Remove Pretty JSON
1. Reinstall Pretty JSON
1. Full quit and restart ST

OR

1. Upgrade Pretty JSON
1. Full quit and restart ST

**Comment by nrabinowitz** [comment] 2020-04-22 16:08
Fix works for me, ty! 🎉

**Comment by etienned** [comment] 2020-04-22 18:01
Fix works for me also, but I really had to restart Sublime after removing the package and before reinstalling it. Just doing a remove/install without quitting Sublime didn't worked.

**Comment by mrunal-badhe** [comment] 2020-04-23 05:56
Yeah. Fix works for me as well. Thanks a lot! :-)

I had tried remove -> reinstall, but then did not quit ST
You HAVE to full quit and restart ST for the fix to work.

**Comment by g-bon** [comment] 2020-04-30 08:03
Workaround works for me too. Thanks

**Comment by cristcost** [comment] 2020-05-06 16:24
thanks, the workaround to reinstall the plugin worked for me at the second attempt

**Comment by kaen98** [comment] 2020-05-20 06:46
> @frank-weindel @mrunal-badhe @nrabinowitz @w84miracle
> 
> @dzhibas for transparency
> 
> This is indeed a PackageControl / ST3 Issue. This happens when moving from a `.no-sublime-package` release to a packaged release. It happens because even though ST unloads the old version, it doesn't exactly purge `importlib` cache so ST still thinks it's installed at `Packages/` and then fails to load it as it now lives at `Installed Packages/`. Doing a full quit of ST should resolve this by forcing the cache to be cleared and it will then be loaded from the correct location.
> 
> **Note**
> This is actually resolved in ST4 and this issue does not occur.
> 
> **Workaround**
> 
> 1. Remove Pretty JSON
> 2. Reinstall Pretty JSON
> 3. Full quit and restart ST
> 
> OR
> 
> 1. Upgrade Pretty JSON
> 2. Full quit and restart ST

thanks!

**Comment by TheSecEng** [comment] 2021-06-09 02:59
Resolved in latest commit

**Closed by TheSecEng** 2021-06-09 02:59 UTC
Labels: bug, investigate
